name: qbox_widget_webview
description: "QBox widget WebView library"
version: 0.3.6
homepage: https://pub.dev/packages/qbox_widget_webview
repository: https://github.com/q19-kz/qbox-widget-webview-flutter
issue_tracker: https://github.com/q19-kz/qbox-widget-webview-flutter/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  permission_handler: ^11.4.0
  simple_pip_mode: ^1.1.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
